project:
  type: website

website:
  title: "Practical programming in Chemistry"
  page-navigation: true
  sidebar:
    - id: main-sidebar
      title: "Home"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - text: Commands summary
          href: cheatsheets.qmd
        - ---
        - section: Lecture 01
        - text: "Tutorial: Configuration"
          href: tutorials/lecture_01/01_setup.qmd
        - text: "Tutorial: GitHub Basics"
          href: tutorials/lecture_01/02_github.qmd
        - text: "Tutorial: SSH Connection"
          href: tutorials/lecture_01/03_ssh_connection.qmd
        - text: "Next steps: Fork and Code"
          href: tutorials/lecture_01/04_next_steps.qmd
        - ---
        - section: Lecture 02
        - text: "Jupyter notebooks"
          href: tutorials/lecture_02/01_jupyter_notebooks.qmd
        - text: "Python basics"
          href: tutorials/lecture_02/02_python_basics.qmd
        - text: "Python structures"
          href: tutorials/lecture_02/03_python_structures.qmd
        - text: "Python iterations"
          href: tutorials/lecture_02/04_python_iterations.qmd
        - ---
        - section: Lecture 03
        - text: "Python functions"
          href: tutorials/lecture_03/01_functions.qmd
        - text: "Python classes"
          href: tutorials/lecture_03/02_classes.qmd
        - text: "Python packages"
          href: tutorials/lecture_03/03_packages.qmd
        - text: "File IO"
          href: tutorials/lecture_03/04_fileio.qmd
        - text: "Error handling"
          href: tutorials/lecture_03/05_errors.qmd
        - ---
        - section: Lecture 04
        - text: "Pandas"
          href: tutorials/lecture_04/01_pandas.qmd
        - text: "Matplotlib"
          href: tutorials/lecture_04/02_matplotlib.qmd
        - text: "Seaborn"
          href: tutorials/lecture_04/03_seaborn.qmd
        - ---
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true