---
title: "Practical Programming for Chemistry"
subtitle: CH-200, EPFL
---


## Content

This course provides a comprehensive and practical introduction to computer programming with a specific focus on its application for chemists and chemical engineers. The course assumes little programming experience and primarily uses Python as the teaching language. The content covers crucial programming concepts like data types, control structures, string processing, functions, and input/output operations. These concepts are taught within the context of chemical tasks. 

The course format consists lessons on diverse topics and hands-on exercise sessions. We will cover the basics of configuring a computer and an introduction to Jupyter(Lab), a popular tool used in data science and cheminformatics. The course will teach basic command line skills, usage of variables, operators, and types, more about operators and conditionals, lists and tuples, iteration, and functions. Lessons cover string methods, dictionaries, packages and modules, file I/O, the use of Git for version control, errors and exception handling, style, comprehensions, and an introduction to Pandas and RDKit for chemical data manipulation. The course will also contain lessons on managing and cleaning data, along with making plots.

<!-- | Week | Topic | Slides | Tutorials |
|--|--|--|--|
|  |Getting started| [Slides 01](slides/lecture_01/){target="_blank"} | [Basic setup](tutorials/lecture_01/01_setup.qmd)|
|  |  |  |[GitHub intro](tutorials/lecture_01/02_github.qmd)| -->